config/routes.rb
Blog::Application.routes.draw do
  

  root 'profile#index'
  resources :posts do
    resources :comments
  end
  resources :profile 
  resources :tags
  resources :authors
  resources :author_sessions, only: [ :new, :create, :destroy ]
  get 'login' => 'author_sessions#new'
  get 'logout' => 'author_sessions#destroy'

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments , dependent: :destroy
  has_many :taggings
  has_many :tags, through: :taggings
  has_attached_file :image
  
  validates :title, presence: true
  validates :body, presence: true
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"], 
                                    styles: {medium: "300x300>", thumb: "100x100>" }
  
  
  def tag_list
    self.tags.collect do |tag|
      tag.name
    end.join(", ")
  end
  
  def tag_list=(tag_string)
    tag_names = tag_string.split(",").collect { |tag| tag.strip.downcase }.uniq
    new_or_found_tags = tag_names.collect {|name| Tag.find_or_create_by(name: name)}
    self.tags = new_or_found_tags
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
 # before_filter :authenticate, except: [:index, :show]
  before_filter :require_login, except: [:index, :show]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @new_comment = Comment.new
    @comment = @post.comments
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :tag_list, :image)
    end

    def authenticate
      authenticate_or_request_with_http_basic do |name, password|
        name == 'admin' && password == 'admin'
      end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post, html: {multipart: true}) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
	<div class="tag">
		<%= f.label :tag_list %><br />
		<%= f.text_field :tag_list %>
	</div>
	<div>
		<% if @post.image.exists? %>
			<%= image_tag @post.image.url %>
		<% end %>
		<%= f.label :image, "Attach a image" %> <br />
		<%= f.file_field :image %>
	</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<table>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= link_to 'Show', post %></td>
        <% if logged_in? %>
          <td><%= link_to 'Edit', edit_post_path(post) %></td>
          <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if logged_in? %>
  <%= link_to 'New Post', new_post_path %>
<% end %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>
	<strong>Tag:</strong>
	<% @post.tags.each do |tag| %>
		<%= link_to tag.name, tag_path(tag) %>
	<% end %>
</p>
<p>
	<% if @post.image.exists? %>
		<%= image_tag @post.image.url %>
	<% end %>
</p>
<% if logged_in? %>
  <%= link_to 'Edit', edit_post_path(@post) %> |
<% end %>

<%= link_to 'Back', posts_path %>

<div id="comments">
    <%= render :partial => @post.comments.reverse%>
</div>

<%= form_for ([@post, @new_comment]), remote: true do |f| %>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>