config/routes.rb
Blog::Application.routes.draw do
  

  root 'profile#index'
  resources :posts do
    resources :comments
  end
  resources :profile 
  resources :tags
  resources :authors
  resources :author_sessions, only: [ :new, :create, :destroy ]
  get 'login' => 'author_sessions#new'
  get 'logout' => 'author_sessions#destroy'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>
	<link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
	<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
	<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
	<![endif]-->

</head>
<body>
	<% if not (current_page?(controller: 'profile', action: 'index'))%>
		<header class="profile_header">
			<div class="container-fluid">
				<div class="navbar-header">
					<a class="navbar-brand" href="#">
						<%= image_tag "main-logo.png" %>
					</a>
				</div>
			</div>
		</header>
		<div class="flash">
			<%= flash.notice %>
		</div>
		<div class="logged_in">
			<% if logged_in? %>
				<span><%= "Logged in as #{current_user.email}" %></span>
				<%= link_to "(logout)", logout_path %>
			<% end %>
		</div>
	<% end %>
	<%= yield %>	
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>  
</body>
</html>